management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'

spring:
  application:
    name: single-eureka-server

server:
  port: 9870
eureka:
  instance:
    hostname: localhost
    appname: single-eureka-server
  client:
    service-url:
      defaultZone: http://localhost:9870/eureka/
    fetch-registry: true
    register-with-eureka: false

