management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      # By default, only 'health' and 'info' are accessible via web
      exposure:
        include: '*'

eureka:
  instance:
    # modify /etc/hosts
    hostname: localhost
    # Either this one or the spring boot name must be the same
    # (it works without setting it too, using the alias UNKNOWN)
    appname: my-eureka-service
  client:
    serviceUrl:
      defaultZone: http://locakhost:9876/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 9876

