management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      # By default, only 'health' and 'info' are accessible via web
      exposure:
        include: '*'

---
spring:
  profiles: peer1
eureka:
  instance:
    # modify /etc/hosts
    hostname: peer1
    # Either this one or the spring boot name must be the same
    # (it works without setting it too, using the alias UNKNOWN)
    appname: my-eureka-cluster
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8761

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    appname: my-eureka-cluster
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8762