appconfig:
  server1: peer1
  server1-port: 9001
  server1-addr: peer1:9001
  server2: peer2
  server2-port: 9002
  server2-addr: peer2:9002
  server3: peer3
  server3-port: 9003
  server3-addr: peer3:9003
  cfg1: cfg1
  cfg1-port: 9101
  cfg2: cfg2
  cfg2-port: 9102
  cfg3: cfg3
  cfg3-port: 9103


eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://${appconfig.server1-addr}/eureka/,http://${appconfig.server2-addr}/eureka/,http://${appconfig.server3-addr}/eureka/

spring:
  application:
    name: cfg-cluster
  cloud:
    config:
      server:
        git:
          # config github address
          uri: https://github.com/aleojiang/my_springcloud_tutorial/
          # configuration file path, multiple paths would be separated by comma ","
          search-paths: config-repository
          # github account
          username: aleojiang
          password: 1q1q1q1q

---
spring:
  profiles: cfg1
eureka:
  instance:
    hostname: ${appconfig.server1}
server:
  port: ${appconfig.cfg1-port}

---
spring:
  profiles: cfg2
eureka:
  instance:
    hostname: ${appconfig.server2}
server:
  port: ${appconfig.cfg2-port}

---
spring:
  profiles: cfg3
eureka:
  instance:
    hostname: ${appconfig.server3}
server:
  port: ${appconfig.cfg3-port}
