pk:
  appconfig:
    eureka-appname: eureka-peer-aware-cluster
    peer1-alias: peer1
    peer2-alias: peer2
    peer1-port: 9000
    peer2-port: 9001
    cfg-appname: cfg-cluster
    cfg1-alias: cfg1
    cfg2-alias: cfg2
    cfg1-port: 9100
    cfg1-port: 9101
    api-appname: api-cluster
    api1-alias: api1
    api2-alias: api2
    api1-port: 9200
    api2-port: 9201

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10

spring:
  cloud:
    config:
      server:
        git:
          # config github address
          uri: https://github.com/aleojiang/my_springcloud_tutorial/
          # configuration file path, multiple paths would be separated by comma ","
          search-paths: config-repository
          # github account
          username: aleojiang
          password: 1q1q1q1q

---
spring:
  profiles: cfg1
  application:
    name: ${pk.appconfig.cfg-appname}
server:
  port: ${pk.appconfig.cfg1-port}
# to make it more interesting, let's have each client registering at a different instance
eureka:
  client:
    service-url:
      defaultZone: http://${pk.appconfig.peer1-alias}:${pk.appconfig.peer1-port}/eureka

---
spring:
  profiles: cfg2
  application:
    name: ${pk.appconfig.cfg-appname}
server:
  port: ${pk.appconfig.cfg2-port}
eureka:
  client:
    service-url:
      defaultZone: http://${pk.appconfig.peer2-alias}:${pk.appconfig.peer2-port}/eureka
