eureka:
  instance:
    lease-renewal-interval-in-seconds: 10

pk:
  appconfig:
    spanish-alias: pk-es
    english-alias: pk-en
    spanish-port: 8084
    english-port: 8085
    peer1-address: peer1:8761
    peer2-address: peer2:8762

---
spring:
  profiles: spanish
  application:
    name: ${pk.appconfig.spanish-alias}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aleojiang/spring-cloud-starter/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: yourname                                        # git仓库的账号
          password: yourpass                                    # git仓库的密码
server:
  port: ${pk.appconfig.spanish-port}
# to make it more interesting, let's have each client registering at a different instance
eureka:
  client:
    service-url:
      defaultZone: http://${pk.appconfig.peer1-address}/eureka

---
spring:
  profiles: english
  application:
    name: ${pk.appconfig.english-alias}
server:
  port: ${pk.appconfig.english-port}
eureka:
  client:
    service-url:
      defaultZone: http://${pk.appconfig.peer2-address}/eureka