eureka:
  instance:
    lease-renewal-interval-in-seconds: 10

pk:
  appconfig:
    conf1-alias: pk-es
    conf2-alias: pk-en
    conf1-port: 8084
    conf2-port: 8085
    peer1-address: peer1:8761
    peer2-address: peer2:8762

spring:
  cloud:
    config:
      server:
        git:
          # config github address
          uri: https://github.com/aleojiang/my_springcloud_tutorial/
          # configuration file path, multiple paths would be separated by comma ","
          search-paths: config-repository
          # github account
          username: aleojiang
          password: 1q1q1q1q

---
spring:
  profiles: conf1
  application:
    name: ${pk.appconfig.conf1-alias}
server:
  port: ${pk.appconfig.conf1-port}
# to make it more interesting, let's have each client registering at a different instance
eureka:
  client:
    service-url:
      defaultZone: http://${pk.appconfig.peer1-address}/eureka

---
spring:
  profiles: conf2
  application:
    name: ${pk.appconfig.conf2-alias}
server:
  port: ${pk.appconfig.conf2-port}
eureka:
  client:
    service-url:
      defaultZone: http://${pk.appconfig.peer2-address}/eureka